import type { NextPage } from 'next'
import Head from 'next/head'
import ProjectList from '../components/ProjectList'
import exampleProjects from "../fixtures/projectExample";
import { Project } from '../models/project-model';

interface Props {
  projects: Project[]
}

export default function Home({ projects }: Props) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <div>
          <ProjectList projects={projects}/>
        </div>
      </div>
    </div>
  )
}


export const getStaticProps = () => {
  const projects: Project[] = exampleProjects;
  return {
    props: {
      projects: projects
    }
  }
}